### ISSUE TITLE
Add the Yay or Nay dialog to better differentiate between nc and fp comments

### ISSUE THREAD

**Issue by mvarendorff** [geisterfurz007/QueenReporter#1]
Because the userscript currently sends back feedback as nc in case of flagging for NLN, there should be a small popup that asks if feedback should be sent as nc or fp.

**Comment by geisterfurz007** [comment]
nc feedback on nln flag is currently disabled until I finish writing the dialog that currently only looks like a floating mess of buttons :)

**Comment by Filnor** [comment]
Isn't every dialog/popup on SO a floating mess of DOM? :P But good to know,
that way I can give manual feedback.
