### ISSUE TITLE
Feedback needed or not needed option on rude flag

### ISSUE THREAD

**Issue by kayesshu** [geisterfurz007/QueenReporter#4]
Have the ability - like with using a checkbox on the Queen script form- to have feedback or no feedback for the rude flag on comments.

**Comment by mvarendorff** [comment]
FYI: The commit above introduces a checkbox next to the Cancel button in the flagging dialog regardless the flagtype which is enabled by default. If you have suggestions regarding placement, etc, feel free to reopen :)
